var group__boards =
[
    [ "Airfy Beacon", "group__board__airfy-beacon.html", "group__board__airfy-beacon" ],
    [ "Arduino Due", "group__board__arduino-due.html", "group__board__arduino-due" ],
    [ "Arduino Mega 2560", "group__board__arduino-mega2560.html", "group__board__arduino-mega2560" ],
    [ "Avsextrem", "group__boards__avsextrem.html", "group__boards__avsextrem" ],
    [ "CC2538DK", "group__board__cc2538dk.html", "group__board__cc2538dk" ],
    [ "Chronos", "group__boards__chronos.html", "group__boards__chronos" ],
    [ "F4VI1", "group__board__f4vi1.html", "group__board__f4vi1" ],
    [ "fox", "group__board__fox.html", "group__board__fox" ],
    [ "IoT-LAB M3 open node", "group__board__iot-lab__M3.html", "group__board__iot-lab__M3" ],
    [ "mbed LPC1768 development kit", "group__board__mbed__lpc1768.html", "group__board__mbed__lpc1768" ],
    [ "MSB-430", "group__boards__msb430.html", "group__boards__msb430" ],
    [ "MSB-430 common", "group__boards__msb430-common.html", "group__boards__msb430-common" ],
    [ "MSB-430H", "group__boards__msb430h.html", "group__boards__msb430h" ],
    [ "MSB-A2", "group__boards__msba2.html", "group__boards__msba2" ],
    [ "MSB-A2 common", "group__boards__msba2-common.html", "group__boards__msba2-common" ],
    [ "MSB-IoT", "group__board__msbiot.html", "group__board__msbiot" ],
    [ "STM32F4Discovery", "group__board__stm32f4discovery.html", "group__board__stm32f4discovery" ],
    [ "Native Board", "group__boards__native.html", "group__boards__native" ],
    [ "OpenMote", "group__board__openmote.html", "group__board__openmote" ],
    [ "phyWAVE-KW22 Board", "group__board__phywave__eval.html", "group__board__phywave__eval" ],
    [ "PCA10000 (nRF51822 Development Kit)", "group__board__pca10000.html", "group__board__pca10000" ],
    [ "PCA10005 (nRF51822 Development Kit)", "group__board__pca10005.html", "group__board__pca10005" ],
    [ "PTTU", "group__boards__pttu.html", "group__boards__pttu" ],
    [ "Redbee Econotag", "group__boards__redbee-econotag.html", "group__boards__redbee-econotag" ],
    [ "Atmel SAM R21 Xplained Pro", "group__board__samr21-xpro.html", "group__board__samr21-xpro" ],
    [ "Spark-Core", "group__board__spark-core.html", "group__board__spark-core" ],
    [ "STM32F0Discovery", "group__board__stm32f0discovery.html", "group__board__stm32f0discovery" ],
    [ "STM32F3Discovery", "group__board__stm32f3discovery.html", "group__board__stm32f3discovery" ],
    [ "TelosB", "group__boards__telosb.html", "group__boards__telosb" ],
    [ "UDOO", "group__board__udoo.html", "group__board__udoo" ],
    [ "WSN430 common", "group__boards__wsn430-common.html", "group__boards__wsn430-common" ],
    [ "WSN430 v1.3b", "group__boards__wsn430-v1__3b.html", "group__boards__wsn430-v1__3b" ],
    [ "WSN430 v1.4", "group__boards__wsn430-v1__4.html", "group__boards__wsn430-v1__4" ],
    [ "Yunjia NRF51822", "group__board__yunjia-nrf51822.html", "group__board__yunjia-nrf51822" ],
    [ "Zolertia Z1", "group__board__z1.html", "group__board__z1" ]
];