Contiki 3.x: cpu/arm/k60/drivers/llwu.h File Reference
llwu.h File Reference
    Provide common UART routines for MK60DZ10.
#include <stdint.h>
#include "K60.h"
#include "synchronization.h"
Typedefs
typedef enum llwu_wakeup_module llwu_wakeup_module_t
Internal modules whose interrupts are mapped to LLWU wake up sources.
typedef enum llwu_wakeup_pin llwu_wakeup_pin_t
enum that maps physical pins to wakeup pin numbers in LLWU module
Enumerations
enum llwu_wakeup_module
Internal modules whose interrupts are mapped to LLWU wake up sources.
enum llwu_wakeup_pin
enum that maps physical pins to wakeup pin numbers in LLWU module
Functions
void llwu_sleep ()
Sleep until some process is polled, ie interrupt occurs.
void llwu_register (llwu_control_t *c)
Register as a controller for llwu.
void llwu_set_allow (llwu_control_t *c, char allow)
Method for a controller to allow or disallow deep sleep.
Detailed Description
    Provide common UART routines for MK60DZ10.
Author
Henrik Makitaavola henri.nosp@m.k@ma.nosp@m.kitaa.nosp@m.vola.nosp@m..se
Joakim Gebart joaki.nosp@m.m.ge.nosp@m.bart@.nosp@m.eist.nosp@m.ec.se
Definition in file llwu.h.
Typedef Documentation
typedef enum llwu_wakeup_module llwu_wakeup_module_t
Internal modules whose interrupts are mapped to LLWU wake up sources.
Wake up source module number: Kinetis Module 0: LPTMR 1: CMP0 2: CMP1 3: CMP2 4: TSI 5: RTC Alarm 6: Reserved 7: RTC Seconds
Other modules CAN NOT be used to wake the CPU from LLS or VLLSx power modes.
typedef enum llwu_wakeup_pin llwu_wakeup_pin_t
enum that maps physical pins to wakeup pin numbers in LLWU module
Other modules CAN NOT be used to wake the CPU from LLS or VLLSx power modes.
Enumeration Type Documentation
enum llwu_wakeup_module
Internal modules whose interrupts are mapped to LLWU wake up sources.
Wake up source module number: Kinetis Module 0: LPTMR 1: CMP0 2: CMP1 3: CMP2 4: TSI 5: RTC Alarm 6: Reserved 7: RTC Seconds
Other modules CAN NOT be used to wake the CPU from LLS or VLLSx power modes.
Definition at line 70 of file llwu.h.
enum llwu_wakeup_pin
enum that maps physical pins to wakeup pin numbers in LLWU module
Other modules CAN NOT be used to wake the CPU from LLS or VLLSx power modes.
Definition at line 85 of file llwu.h.
Function Documentation
void llwu_register (llwu_control_t * c)
Register as a controller for llwu.
Parameters
c Controller struct.
Definition at line 47 of file llwu.c.
References list_add().
Referenced by main().
void llwu_set_allow (llwu_control_t * c, char allow)
Method for a controller to allow or disallow deep sleep.
Parameters
c Control struct
allow 0 to disable deep sleep, other than 0 to allow.
Definition at line 54 of file llwu.c.
Referenced by main().