var searchData=
[
  ['spark_2dcore',['Spark-Core',['../group__board__spark-core.html',1,'']]],
  ['stm32f0discovery',['STM32F0Discovery',['../group__board__stm32f0discovery.html',1,'']]],
  ['stm32f3discovery',['STM32F3Discovery',['../group__board__stm32f3discovery.html',1,'']]],
  ['stm32f4discovery',['STM32F4Discovery',['../group__board__stm32f4discovery.html',1,'']]],
  ['startup_20and_20configuration',['Startup and Configuration',['../group__core__internal.html',1,'']]],
  ['scheduler',['Scheduler',['../group__core__sched.html',1,'']]],
  ['synchronization',['Synchronization',['../group__core__sync.html',1,'']]],
  ['samr21g18a_20definitions',['SAMR21G18A definitions',['../group__cpu__specific__SAMR21G18A__definitions.html',1,'']]],
  ['stm32f0',['STM32F0',['../group__cpu__stm32f0.html',1,'']]],
  ['stm32f1',['STM32F1',['../group__cpu__stm32f1.html',1,'']]],
  ['stm32f3',['STM32F3',['../group__cpu__stm32f3.html',1,'']]],
  ['stm32f4',['STM32F4',['../group__cpu__stm32f4.html',1,'']]],
  ['spi',['SPI',['../group__driver__periph__spi.html',1,'']]],
  ['servo_20motor_20driver',['Servo Motor Driver',['../group__driver__servo.html',1,'']]],
  ['srf02_20ultrasonic_20range_20sensor',['SRF02 ultrasonic range sensor',['../group__driver__srf02.html',1,'']]],
  ['srf08_20ultrasonic_20range_20sensor',['SRF08 ultrasonic range sensor',['../group__driver__srf08.html',1,'']]],
  ['sdhc_20peripheral_20access_20layer',['SDHC Peripheral Access Layer',['../group__SDHC__Peripheral__Access__Layer.html',1,'']]],
  ['sdhc_20_2d_20register_20accessor_20macros',['SDHC - Register accessor macros',['../group__SDHC__Register__Accessor__Macros.html',1,'']]],
  ['sdhc_20register_20masks',['SDHC Register Masks',['../group__SDHC__Register__Masks.html',1,'']]],
  ['sht11',['SHT11',['../group__sht11.html',1,'']]],
  ['sim_20peripheral_20access_20layer',['SIM Peripheral Access Layer',['../group__SIM__Peripheral__Access__Layer.html',1,'']]],
  ['sim_20_2d_20register_20accessor_20macros',['SIM - Register accessor macros',['../group__SIM__Register__Accessor__Macros.html',1,'']]],
  ['sim_20register_20masks',['SIM Register Masks',['../group__SIM__Register__Masks.html',1,'']]],
  ['smc_20peripheral_20access_20layer',['SMC Peripheral Access Layer',['../group__SMC__Peripheral__Access__Layer.html',1,'']]],
  ['smc_20_2d_20register_20accessor_20macros',['SMC - Register accessor macros',['../group__SMC__Register__Accessor__Macros.html',1,'']]],
  ['smc_20register_20masks',['SMC Register Masks',['../group__SMC__Register__Masks.html',1,'']]],
  ['spi_20peripheral_20access_20layer',['SPI Peripheral Access Layer',['../group__SPI__Peripheral__Access__Layer.html',1,'']]],
  ['spi_20_2d_20register_20accessor_20macros',['SPI - Register accessor macros',['../group__SPI__Register__Accessor__Macros.html',1,'']]],
  ['spi_20register_20masks',['SPI Register Masks',['../group__SPI__Register__Masks.html',1,'']]],
  ['system',['System',['../group__sys.html',1,'']]],
  ['sha264',['SHA264',['../group__sys__sha256.html',1,'']]],
  ['shell',['Shell',['../group__sys__shell.html',1,'']]]
];
