var searchData=
[
  ['redbee_20econotag',['Redbee Econotag',['../group__boards__redbee-econotag.html',1,'']]],
  ['registers_20access_20definitions',['Registers Access Definitions',['../group__cpu__specific__SAMR21G18A__reg.html',1,'']]],
  ['random',['Random',['../group__driver__periph__random.html',1,'']]],
  ['rtc',['RTC',['../group__driver__periph__rtc.html',1,'']]],
  ['rtt',['RTT',['../group__driver__periph__rtt.html',1,'']]],
  ['rgb_2dled_20driver',['RGB-LED driver',['../group__driver__rgbled.html',1,'']]],
  ['rcm_20peripheral_20access_20layer',['RCM Peripheral Access Layer',['../group__RCM__Peripheral__Access__Layer.html',1,'']]],
  ['rcm_20_2d_20register_20accessor_20macros',['RCM - Register accessor macros',['../group__RCM__Register__Accessor__Macros.html',1,'']]],
  ['rcm_20register_20masks',['RCM Register Masks',['../group__RCM__Register__Masks.html',1,'']]],
  ['rfsys_20peripheral_20access_20layer',['RFSYS Peripheral Access Layer',['../group__RFSYS__Peripheral__Access__Layer.html',1,'']]],
  ['rfsys_20_2d_20register_20accessor_20macros',['RFSYS - Register accessor macros',['../group__RFSYS__Register__Accessor__Macros.html',1,'']]],
  ['rfsys_20register_20masks',['RFSYS Register Masks',['../group__RFSYS__Register__Masks.html',1,'']]],
  ['rfvbat_20peripheral_20access_20layer',['RFVBAT Peripheral Access Layer',['../group__RFVBAT__Peripheral__Access__Layer.html',1,'']]],
  ['rfvbat_20_2d_20register_20accessor_20macros',['RFVBAT - Register accessor macros',['../group__RFVBAT__Register__Accessor__Macros.html',1,'']]],
  ['rfvbat_20register_20masks',['RFVBAT Register Masks',['../group__RFVBAT__Register__Masks.html',1,'']]],
  ['rng_20peripheral_20access_20layer',['RNG Peripheral Access Layer',['../group__RNG__Peripheral__Access__Layer.html',1,'']]],
  ['rng_20_2d_20register_20accessor_20macros',['RNG - Register accessor macros',['../group__RNG__Register__Accessor__Macros.html',1,'']]],
  ['rng_20register_20masks',['RNG Register Masks',['../group__RNG__Register__Masks.html',1,'']]],
  ['rtc_20peripheral_20access_20layer',['RTC Peripheral Access Layer',['../group__RTC__Peripheral__Access__Layer.html',1,'']]],
  ['rtc_20_2d_20register_20accessor_20macros',['RTC - Register accessor macros',['../group__RTC__Register__Accessor__Macros.html',1,'']]],
  ['rtc_20register_20masks',['RTC Register Masks',['../group__RTC__Register__Masks.html',1,'']]],
  ['random',['Random',['../group__sys__random.html',1,'']]]
];
