var searchData=
[
  ['pca10000_20_28nrf51822_20development_20kit_29',['PCA10000 (nRF51822 Development Kit)',['../group__board__pca10000.html',1,'']]],
  ['pca10005_20_28nrf51822_20development_20kit_29',['PCA10005 (nRF51822 Development Kit)',['../group__board__pca10005.html',1,'']]],
  ['phywave_2dkw22_20board',['phyWAVE-KW22 Board',['../group__board__phywave__eval.html',1,'']]],
  ['pttu',['PTTU',['../group__boards__pttu.html',1,'']]],
  ['power_20management',['Power Management',['../group__core__lpm.html',1,'']]],
  ['peripheral_20software_20api',['Peripheral Software API',['../group__cpu__specific__SAMR21G18A__api.html',1,'']]],
  ['peripheral_20base_20address_20definitions',['Peripheral Base Address Definitions',['../group__cpu__specific__SAMR21G18A__base.html',1,'']]],
  ['peripheral_20ids_20definitions',['Peripheral Ids Definitions',['../group__cpu__specific__SAMR21G18A__id.html',1,'']]],
  ['port_20definitions',['PORT Definitions',['../group__cpu__specific__SAMR21G18A__port.html',1,'']]],
  ['peripheral_20drivers',['Peripheral drivers',['../group__driver__periph.html',1,'']]],
  ['pwm',['PWM',['../group__driver__periph__pwm.html',1,'']]],
  ['pir_20motion_20sensor',['PIR Motion Sensor',['../group__driver__pir.html',1,'']]],
  ['protocol_20multiplex',['Protocol multiplex',['../group__net__mmstack.html',1,'']]],
  ['pdb_20peripheral_20access_20layer',['PDB Peripheral Access Layer',['../group__PDB__Peripheral__Access__Layer.html',1,'']]],
  ['pdb_20_2d_20register_20accessor_20macros',['PDB - Register accessor macros',['../group__PDB__Register__Accessor__Macros.html',1,'']]],
  ['pdb_20register_20masks',['PDB Register Masks',['../group__PDB__Register__Masks.html',1,'']]],
  ['pit_20peripheral_20access_20layer',['PIT Peripheral Access Layer',['../group__PIT__Peripheral__Access__Layer.html',1,'']]],
  ['pit_20_2d_20register_20accessor_20macros',['PIT - Register accessor macros',['../group__PIT__Register__Accessor__Macros.html',1,'']]],
  ['pit_20register_20masks',['PIT Register Masks',['../group__PIT__Register__Masks.html',1,'']]],
  ['packet_20buffer',['Packet buffer',['../group__pktbuf.html',1,'']]],
  ['packet_20queue',['Packet Queue',['../group__pktqueue.html',1,'']]],
  ['pmc_20peripheral_20access_20layer',['PMC Peripheral Access Layer',['../group__PMC__Peripheral__Access__Layer.html',1,'']]],
  ['pmc_20_2d_20register_20accessor_20macros',['PMC - Register accessor macros',['../group__PMC__Register__Accessor__Macros.html',1,'']]],
  ['pmc_20register_20masks',['PMC Register Masks',['../group__PMC__Register__Masks.html',1,'']]],
  ['port_20peripheral_20access_20layer',['PORT Peripheral Access Layer',['../group__PORT__Peripheral__Access__Layer.html',1,'']]],
  ['port_20_2d_20register_20accessor_20macros',['PORT - Register accessor macros',['../group__PORT__Register__Accessor__Macros.html',1,'']]],
  ['port_20register_20masks',['PORT Register Masks',['../group__PORT__Register__Masks.html',1,'']]],
  ['posix_20wrapper_20for_20riot',['POSIX wrapper for RIOT',['../group__posix.html',1,'']]],
  ['posix_20threads',['POSIX threads',['../group__pthread.html',1,'']]],
  ['pipe_20ipc',['Pipe IPC',['../group__sys__pipe.html',1,'']]],
  ['ps',['PS',['../group__sys__ps.html',1,'']]]
];
